version: '3.2'

services:
  app:
    build: .
    ports:
      - "0.0.0.0:8081:8080"
    restart: always
    volumes:
      - appdb:/app/backend/database
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  appdb: