FROM alpine:latest AS build-frontend

ADD https://github.com/mint-lang/mint/releases/download/0.16.1/mint-0.16.1-linux /bin/mint
RUN chmod +x /bin/mint

WORKDIR /app
COPY frontend/mint.json .
COPY frontend/assets/ ./assets
COPY frontend/tests/ ./tests
COPY frontend/source/ ./source
COPY frontend/.env ./.env
RUN mint build --env .env --skip-service-worker

FROM python:3.9-slim AS server
WORKDIR /app/backend
COPY backend/.env ./.env
COPY backend/requirements.txt .
COPY backend/mgz ./mgz
RUN pip install -r requirements.txt --no-cache-dir
COPY --from=build-frontend /app/dist ../frontend/dist/
# RUN false | cp -i ./database/app.template.db /app/database/app.db
COPY database/app.template.db /app/database/app.template.db
COPY backend/*.py ./
COPY backend/src/*.py ./src/

EXPOSE 8080
STOPSIGNAL SIGTERM
WORKDIR "/app/backend"
ENTRYPOINT [ "python3", "-m", "main.py" ]
